# Generated by Django 6.0.3 on 2026-04-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reocurrance',
            field=models.CharField(choices=[('daily', 'daily'), ('weekly', 'weekly'), ('biweekly', 'biweekly'), ('monthly', 'monthly'), ('trimonthly', 'trimonthly'), ('biyearly', 'biyearly'), ('anually', 'anually')], db_index=True, default='monthly', max_length=20),
            preserve_default=False,
        ),
    ]
