# Generated by Django 6.0.3 on 2026-06-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_reocurrance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='reocurrance',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Biweekly', 'Biweekly'), ('Monthly', 'Monthly'), ('Trimonthly', 'Trimonthly'), ('Biyearly', 'Biyearly'), ('Anual', 'Anual')], db_index=True, max_length=20),
        ),
    ]
