# Generated by Django 6.0.3 on 2026-04-04 02:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subhub', '0002_remove_subscription_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='category',
            field=models.CharField(choices=[('fixed', 'fixed'), ('entertainment', 'entertainment'), ('groceries', 'groceries'), ('AI', 'AI'), ('education', 'education'), ('loans', 'loans'), ('other', 'other')], db_index=True, default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='reocurrance',
            field=models.CharField(choices=[('daily', 'daily'), ('weekly', 'weekly'), ('biweekly', 'biweekly'), ('monthly', 'monthly'), ('trimonthly', 'trimonthly'), ('biyearly', 'biyearly'), ('anually', 'anually')], db_index=True, default=9.87166831194472e-05, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='due_date',
            field=models.DateField(),
        ),
    ]
