# Generated by Django 6.0.3 on 2026-04-04 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subhub', '0003_subscription_category_subscription_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='price',
            field=models.FloatField(default=0.0007897334649555775, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
