# Generated by Django 6.0.3 on 2026-04-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subhub', '0006_alter_subscription_reocurrance'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='reocurranceDays',
            field=models.DecimalField(choices=[(1, '1'), (7, '7'), (14, '14'), (31, '31'), (93, '93'), (183, '183'), (365, '365')], db_index=True, decimal_places=5, default=31.0, max_digits=90),
            preserve_default=False,
        ),
    ]
