# Generated by Django 6.0.3 on 2026-04-07 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subhub', '0007_subscription_reocurrancedays'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='reocurranceDays',
        ),
    ]
