# Generated by Django 6.0.3 on 2026-04-07 12:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subhub', '0008_remove_subscription_reocurrancedays'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
