# Generated by Django 6.0.3 on 2026-06-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subhub', '0009_subscription_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
