# Generated by Django 6.0.3 on 2026-06-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subhub', '0011_alter_subscription_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='link',
            field=models.CharField(default=0, max_length=2000),
            preserve_default=False,
        ),
    ]
