# Generated by Django 6.0.3 on 2026-06-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subhub', '0012_subscription_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='link',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
